<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="wv589" name="testCases.KontaktPageTest" tests="4" failures="0" timestamp="22 Jun 2017 10:08:06 GMT" time="58.213" errors="1">
  <testcase name="formfillUp" time="15.450" classname="testCases.KontaktPageTest">
    <error type="java.lang.AssertionError" message="Please enter correct email id expected [Die Nachricht wurde erfolgreich 端bermittelt.] but found [Bitte geben Sie eine g端ltige E-Mail-Adresse ein.]">
      <![CDATA[java.lang.AssertionError: Please enter correct email id expected [Die Nachricht wurde erfolgreich 端bermittelt.] but found [Bitte geben Sie eine g端ltige E-Mail-Adresse ein.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at pageObjects.KontaktPage.formvalidation(KontaktPage.java:86)
	at pageObjects.KontaktPage.formSubmit(KontaktPage.java:67)
	at testCases.KontaktPageTest.formfillUp(KontaktPageTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- formfillUp -->
  <testcase name="formfillUp" time="13.697" classname="testCases.KontaktPageTest"/>
  <testcase name="formfillUp" time="14.216" classname="testCases.KontaktPageTest"/>
  <testcase name="formfillUp" time="14.850" classname="testCases.KontaktPageTest"/>
</testsuite> <!-- testCases.KontaktPageTest -->
